Online Course/lab3_template/myproject/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('onlinecourse/', include('onlinecourse.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)\
 + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

Online Course/lab3_template/onlinecourse/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from . import views

app_name = 'onlinecourse'
urlpatterns = [

    path(route='course/<int:pk>/enroll/', view=views.EnrollView.as_view(), name='enroll'),
    path(route='', view=views.CourseListView.as_view(), name='popular_course_list'),
    path(route='course/<int:pk>/', view=views.CourseDetailsView.as_view(), name='course_details'),

    # Authentication related urls
    path('registration/', views.registration_request, name='registration'),
    path('login/', views.login_request, name='login'),
    path('logout/', views.logout_request, name='logout'),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)\
 + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

Online Course/lab3_template/onlinecourse/models.py
import sys
from django.utils.timezone import now
try:
    from django.db import models
except Exception:
    print("There was an error loading django modules. Do you have django installed?")
    sys.exit()

from django.conf import settings
import uuid


# Instructor model
class Instructor(models.Model):
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
    )
    full_time = models.BooleanField(default=True)
    total_learners = models.IntegerField()

    def __str__(self):
        return self.user.username


# Learner model
class Learner(models.Model):
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
    )
    STUDENT = 'student'
    DEVELOPER = 'developer'
    DATA_SCIENTIST = 'data_scientist'
    DATABASE_ADMIN = 'dba'
    OCCUPATION_CHOICES = [
        (STUDENT, 'Student'),
        (DEVELOPER, 'Developer'),
        (DATA_SCIENTIST, 'Data Scientist'),
        (DATABASE_ADMIN, 'Database Admin')
    ]
    occupation = models.CharField(
        null=False,
        max_length=20,
        choices=OCCUPATION_CHOICES,
        default=STUDENT
    )
    social_link = models.URLField(max_length=200)

    def __str__(self):
        return self.user.username + "," + \
                self.occupation


# Course model
class Course(models.Model):
    name = models.CharField(null=False, max_length=30, default='online course')
    image = models.ImageField(upload_to='course_images/')
    description = models.CharField(max_length=1000)
    pub_date = models.DateField(null=True)
    instructors = models.ManyToManyField(Instructor)
    users = models.ManyToManyField(settings.AUTH_USER_MODEL, through='Enrollment')
    total_enrollment = models.IntegerField(default=0)
    is_enrolled = False

    def __str__(self):
        return "Name: " + self.name + "," + \
                "Description: " + self.description


# Lesson model
class Lesson(models.Model):
    title = models.CharField(max_length=200, default="title")
    order = models.IntegerField(default=0)
    course = models.ForeignKey(Course, on_delete=models.CASCADE)
    content = models.TextField()


# Enrollment model
class Enrollment(models.Model):
    AUDIT = 'audit'
    HONOR = 'honor'
    BETA = 'BETA'
    COURSE_MODES = [
        (AUDIT, 'Audit'),
        (HONOR, 'Honor'),
        (BETA, 'BETA')
    ]
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    course = models.ForeignKey(Course, on_delete=models.CASCADE)
    date_enrolled = models.DateField(default=now)
    mode = models.CharField(max_length=5, choices=COURSE_MODES, default=AUDIT)
    rating = models.FloatField(default=5.0)

Online Course/lab3_template/onlinecourse/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from .models import Course, Lesson, Enrollment
from django.contrib.auth.models import User
from django.shortcuts import get_object_or_404, render, redirect
from django.http import Http404
from django.urls import reverse
from django.views import generic, View
from collections import defaultdict
from django.contrib.auth import login, logout, authenticate
import logging
# Get an instance of a logger
logger = logging.getLogger(__name__)

# Create your views here.

# Create authentication related views


def registration_request(request):
    context = {}
    if request.method == 'GET':
        return render(request, 'onlinecourse/user_registration.html', context)
    elif request.method == 'POST':
        # Check if user exists
        username = request.POST['username']
        password = request.POST['psw']
        first_name = request.POST['firstname']
        last_name = request.POST['lastname']
        user_exist = False
        try:
            User.objects.get(username=username)
            user_exist = True
        except:
            logger.debug("{} is new user".format(username))
        if not user_exist:
            user = User.objects.create_user(username=username, first_name=first_name, last_name=last_name,
                                            password=password)
            login(request, user)
            return redirect("onlinecourse:popular_course_list")
        else:
            context['message'] = "User already exists."
            return render(request, 'onlinecourse/user_registration.html', context)


def login_request(request):
    context = {}
    if request.method == "POST":
        username = request.POST['username']
        password = request.POST['psw']
        user = authenticate(username=username, password=password)
        print(user)
        if user is not None:
            login(request, user)
            return redirect('onlinecourse:popular_course_list')
        else:
            context['message'] = "Invalid username or password."
            return render(request, 'onlinecourse/user_login.html', context)
    else:
        return render(request, 'onlinecourse/user_login.html', context)


def logout_request(request):
    logout(request)
    return redirect('onlinecourse:popular_course_list')


# Add a class-based course list view
class CourseListView(generic.ListView):
    template_name = 'onlinecourse/course_list.html'
    context_object_name = 'course_list'

    def get_queryset(self):
       courses = Course.objects.order_by('-total_enrollment')[:10]
       return courses


# Add a generic course details view
class CourseDetailsView(generic.DetailView):
    model = Course
    template_name = 'onlinecourse/course_detail.html'


class EnrollView(View):

    # Handles get request
    def post(self, request, *args, **kwargs):
        course_id = kwargs.get('pk')
        course = get_object_or_404(Course, pk=course_id)
        # Create an enrollment
        course.total_enrollment += 1
        course.save()
        return HttpResponseRedirect(reverse(viewname='onlinecourse:course_details', args=(course.id,)))

Online Course/lab3_template/onlinecourse/templates/onlinecourse/course_detail.html
<!DOCTYPE html>
<html lang="en">
<!-- <head>
        {% load static %}
    <meta charset="UTF-8">
</head> -->
<head>
    {% load static %}
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <meta charset="UTF-8">
    <title>Online Courses</title>
</head>

<body>
<!-- Add a Navigation bar -->
<nav class="navbar navbar-light bg-light">
    <div class="container-fluid">
        <div class="navbar-header">
            <a class="navbar-brand" href="{% url 'onlinecourse:popular_course_list' %}">Online Course</a>
        </div>
        <ul class="nav navbar-nav navbar-right">
            {% if user.is_authenticated %}
            <li>
                <a class="btn btn-link" href="#">{{ user.first_name }}({{ user.username }})</a>
                <a class="btn btn-link" href="{% url 'onlinecourse:logout' %}">Logout</a>
            </li>
            {% else %}
            <li>
                <form class="form-inline" action="{% url 'onlinecourse:login' %}" method="post">
                    {% csrf_token %}
                    <div class="input-group">
                        <input type="text" class="form-control" placeholder="Username" name="username" >
                        <input type="password" class="form-control" placeholder="Password" name="psw" >
                        <button class="btn btn-primary" type="submit">Login</button>
                        <a class="btn btn-link" href="{% url 'onlinecourse:registration' %}">Sign Up</a>
                    </div>
                </form>
            </li>
            {% endif %}
        </ul>
    </div>
</nav>

<div class="container"> <!--Stylize the root div with .container class -->
    <h2>{{ course.name }}</h2>
    <div class="card-columns-vertical"> <!--Stylize the second level card columns div with .card-columns-vertical class-->
        {% for lesson in course.lesson_set.all %}
        <div class="card"> <!--Stylize the third level lesson div with .card class-->
            <div class="card-header">Lesson {{ forloop.counter }}: {{ lesson.title }}</div> <!--Stylize the fourth level lesson header  div with .card-header class-->
            <div class="card-body">{{lesson.content}}</div>  <!--Stylize the fifth level lesson content div with .card-body class-->
        </div>
        {% endfor %}
    </div>
</div>
</body>

</html>

Online Course/lab3_template/onlinecourse/templates/onlinecourse/course_list.html
<!DOCTYPE html>
<html lang="en">
<!-- <head>
    {% load static %}
    <meta charset="UTF-8">
    <title>Online Courses</title>
</head> -->
<head>
    {% load static %}
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <meta charset="UTF-8">
    <title>Online Courses</title>
</head>
<body>
<!-- Add a Navigation bar -->
<!-- <nav class="navbar navbar-light bg-light">
    <div class="container-fluid">
        <div class="navbar-header">
                <a class="navbar-brand" href="#">Online Course</a>
        </div>
    </div>
</nav>  

<ul>
    <li>
    {% if user.is_authenticated %}
        <a href="#">{{ user.first_name }}({{ user.username }})</a>
        <a href="{% url 'onlinecourse:logout' %}">Logout</a>
    {% else %}
    </li>
    <li>
        <form action="{% url 'onlinecourse:login' %}" method="post">
            {% csrf_token %}
            <div >
                <input type="text" placeholder="Username" name="username" >
                <input type="password" placeholder="Username" name="psw" >
                <button type="submit">Login</button>
                <a  href="{% url 'onlinecourse:registration' %}">Sign Up</a>
            </div>
        </form>
    </li>
    {% endif %} -->
    <nav class="navbar navbar-light bg-light">
        <div class="container-fluid">
            <div class="navbar-header">
                <a class="navbar-brand" href="#">Online Course</a>
            </div>
            <ul class="nav navbar-nav navbar-right">
                {% if user.is_authenticated %}
                <li>
                    <a class="btn btn-link" href="#">{{ user.first_name }}({{ user.username }})</a>
                    <a class="btn btn-link" href="{% url 'onlinecourse:logout' %}">Logout</a>
                </li>
                {% else %}
                <li>
                    <form class="form-inline" action="{% url 'onlinecourse:login' %}" method="post">
                        {% csrf_token %}
                        <div class="input-group">
                            <input type="text" class="form-control" placeholder="Username" name="username" >
                            <input type="password" class="form-control" placeholder="Password" name="psw" >
                            <button class="btn btn-primary" type="submit">Login</button>
                            <a class="btn btn-link" href="{% url 'onlinecourse:registration' %}">Sign Up</a>
                        </div>
                    </form>
                </li>
                {% endif %}
            </ul>
        </div>
    </nav>
</ul>

<!-- Course list section -->
{% if course_list %}
    <div class="container"> <!--Style root div with .container class -->
        <div class="card-deck"> <!--Style second div with .card-deck class -->
            {% for course in course_list %}
            <div class="card" style="width: 36rem;"> <!--Style third level div with .card class -->
                <img class="card-img-left" src="{{MEDIA_URL}}/{{ course.image }}" width="240px" height="240px"
                            alt="Course image"> <!--Style card image with .card-img-left class -->
                <div class="card-body bg-light"> <!--Style root div with .card-body and .bg-light class -->
                    <h5 class="card-title">{{ course.name }}, <span class="text-success"> <!--Style h5 with .card-title and span with .text-success class -->
                                {{ course.total_enrollment}} enrolled</span></h5>
                    <p class="card-text">{{ course.description}}</p> <!--Style card description with .card-text class -->
                    <form action="{% url 'onlinecourse:enroll' course.id %}" method="post">
                        {% csrf_token %}
                        <input class="btn btn-primary" type="submit"
                                value="Enroll"> <!--Style Enroll button with .btn and .btn-primary class -->
                    </form>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
{% else %}
    <p>No courses are available.</p>

{% endif %}
</body>
</html>

Online Course/lab3_template/onlinecourse/templates/onlinecourse/user_login.html
<!DOCTYPE html>
<html lang="en">
<!-- <head>
    <meta charset="UTF-8">
    {% load static %}
</head> -->
<head>
  {% load static %}
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
  <meta charset="UTF-8">
  <title>Online Courses</title>
</head>
<body>

<!-- Add a Navigation bar -->
<nav class="navbar navbar-light bg-light">
  <div class="container-fluid">
      <div class="navbar-header">
        <a class="navbar-brand" href="{% url 'onlinecourse:popular_course_list' %}">Online Course</a>
      </div>
      <ul class="nav navbar-nav navbar-right">
          {% if user.is_authenticated %}
          <li>
              <a class="btn btn-link" href="#">{{ user.first_name }}({{ user.username }})</a>
              <a class="btn btn-link" href="{% url 'onlinecourse:logout' %}">Logout</a>
          </li>
          {% else %}
          <li>
              <form class="form-inline" action="{% url 'onlinecourse:login' %}" method="post">
                  {% csrf_token %}
                  <div class="input-group">
                      <input type="text" class="form-control" placeholder="Username" name="username" >
                      <input type="password" class="form-control" placeholder="Password" name="psw" >
                      <button class="btn btn-primary" type="submit">Login</button>
                      <a class="btn btn-link" href="{% url 'onlinecourse:registration' %}">Sign Up</a>
                  </div>
              </form>
          </li>
          {% endif %}
      </ul>
  </div>
</nav>

<!-- Stylize Login form -->
<form action="{% url 'onlinecourse:login' %}" method="post">
  {% csrf_token %}
  <div class="container"> <!--Stylize root div with .container class -->
    <h1>Login</h1>
    <div class="form-group"> <!--Stylize second div with .form-group class -->
      <label for="username"><b>User Name: </b></label>
      <input id="username" class = "form-control" type="text" placeholder="Enter User Name: " name="username" required> <!--Stylize input with .form-control class -->
      <label for="psw"><b>Password: </b></label>
      <input id="psw" type="password" class = "form-control" placeholder="Enter Password: " name="psw" required> <!--Stylize input with .form-control class -->
    </div>
    {% if message %}
    <div class="alert alert-warning"> <!--Stylize the message paragraph with .alert and .alert-warning class -->
        {{ message }}
      </div>
    {% endif %}
    <button class="btn btn-primary" type="submit">Login</button> <!--Stylize button with .btn and .btn-primary class -->
  </div>
</form>
</body>

Online Course/lab3_template/onlinecourse/templates/onlinecourse/user_registration.html
<!DOCTYPE html>
<html lang="en">
<!-- <head>
    <meta charset="UTF-8">
    {% load static %}
</head> -->
<head>
  {% load static %}
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
  <meta charset="UTF-8">
  <title>Online Courses</title>
</head>
<body>

<!-- Add a Navigation bar --><nav class="navbar navbar-light bg-light">
    <div class="container-fluid">
      <div class="navbar-header">
        <a class="navbar-brand" href="{% url 'onlinecourse:popular_course_list' %}">Online Course</a>
      </div>
      <ul class="nav navbar-nav navbar-right">
          {% if user.is_authenticated %}
          <li>
              <a class="btn btn-link" href="#">{{ user.first_name }}({{ user.username }})</a>
              <a class="btn btn-link" href="{% url 'onlinecourse:logout' %}">Logout</a>
          </li>
          {% else %}
          <li>
              <form class="form-inline" action="{% url 'onlinecourse:login' %}" method="post">
                  {% csrf_token %}
                  <div class="input-group">
                      <input type="text" class="form-control" placeholder="Username" name="username" >
                      <input type="password" class="form-control" placeholder="Password" name="psw" >
                      <button class="btn btn-primary" type="submit">Login</button>
                      <a class="btn btn-link" href="{% url 'onlinecourse:registration' %}">Sign Up</a>
                  </div>
              </form>
          </li>
          {% endif %}
      </ul>
  </div>
</nav>

<!-- Stylize Registration form -->
<form action="{% url 'onlinecourse:registration' %}" method="post">
  <div class="container"> <!--Style root div with .container class -->
    {% csrf_token %}
    <h1>Sign Up</h1>
    <hr>
    <div class="form-group"> <!--Style second div with .form-group class -->
        <label for="username"><b>User Name</b></label>
        <input type="text" class="form-control" placeholder="Enter User Name: " name="username" required> <!--Style input with .form-control class -->
        <label for="firstname"><b>First Name</b></label>
        <input type="text" class="form-control" placeholder="Enter First Name: " name="firstname" required> <!--Style input with .form-control class -->
        <label for="lastname"><b>Last Name</b></label>
        <input type="text" class="form-control" placeholder="Enter Last Name: " name="lastname" required> <!--Style input with .form-control class -->
        <label for="psw"><b>Password</b></label>
        <input type="password" class="form-control" placeholder="Enter Password: " name="psw" required> <!--Style input with .form-control class -->
        {% if message %}
        <div class="alert alert-warning"> <!--Style the message paragraph with .alert and .alert-warning class -->
            {{ message }}
        </div>
        {% endif %}
        <button class="btn btn-primary" type="submit">Sign up</button> <!--Style button with .btn and .btn-primary class -->
    </div>
  </div>
</form>

</body>
</html>